package finale.events;

import finale.controllers.GameController;
import finale.views.GameView;
/**
Interface for events generated by the game

@author  David Liu, Brandon Liu, Yuzhi Zheng
@version June 4th, 2008
@author team FINALE
*/
public interface GameEvent {
	/**
	   The action that the GameEvent does.
	   @param ctl : the controller to sent actions to
	   @param view : the view to draw the actions
	 */
	void action(GameController ctl, GameView view);
}
